name = "DifferenceEquations"
uuid = "e0ca9c66-1f9e-11ec-127a-1304ce62169c"
authors = ["Cameron Pfiffer <cameron@pfiffer.org> and contributors"]
version = "0.4.1"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CommonSolve = "0.2"
Distributions = "0.25"
DistributionsAD = "0.6"
SciMLBase = "1.19"
StatsBase = "0.33"
julia = "1.6"
